### PR TITLE
Add YJS collaboration plugin

### PR DESCRIPTION
**Pull request by nevecex**
## Background

This PR adds YJS collaboration plugin that is used in the react version. Using the YJS server this allows multiple editors to collaborate on a document. 

Added the example editor that can be used to run and test the feature in docs. Resolves https://github.com/wobsoriano/lexical-vue/issues/7

## Demo
https://github.com/wobsoriano/lexical-vue/assets/10382614/5bddb31d-a0c8-457b-a96b-26273cce01a0

### CODE REVIEW

**Comment by zswaff** [comment]
Resolves #7

**Comment by wobsoriano** [comment]
Reviewing this tonight. Should probably be done this weekend. I'll let you guys know if I encounter any issues :)

**Comment by zswaff** [comment]
Awesome, thanks! We'll be around!

**Review by wobsoriano — APPROVED** [review]
This looks good to me. Compared with the React version as well.

Some nitpicks like using `!==` instead of `!=` but I can update that.

Thank you! Appreciate the PR.

**Pull request merged**
